### PR TITLE
Feature/add footer

### PR DESCRIPTION
**Pull request by DusanSacha**
#15

### CODE REVIEW

**Comment by DusanSacha** [comment]
Not sure now why commit b51f8af was added to this push from my local again. But it should be OK. Let me know if not.

Thanks!

**Comment by ovidiu-bute-hs** [comment]
The design is a bit off. 

screen shot 2017-04-26 at 3 41 33 pm

I'd also like to have a link towards the Organization, not just my own GitHub account (I'm sure you'll agree 😄 ). 

Let's hold off a bit on this one until the core game loop is finished and we can talk about a nicer design.

**Comment by DusanSacha** [comment]
Sure, agree!

**Comment by DusanSacha** [comment]
I will close and delete this PR and start a new one for the footer. It is already a bit old and making a new one will be the easiest.

**Pull request closed without merging**
