### PR TITLE
airbnb lint + dependencies update

### PR DESCRIPTION
**Pull request by DusanSacha**
Solving #28 

- added only `eslint-config-airbnb`. Other peer dependencies for `eslint-config-airbnb`are already part of `react-scripts`.

- `react-scripts` was updated. So that we have actual dependencies for `eslint-config-airbnb`

- removed `React.PropTypes` from code. Used `prop-types` library instead

Actually I don't see any other warning in the browser console. However I still can see a lot of warnings in VSCode - using ESLint extension. Check the screenshot. Do you think these should be solved as well?

react_puzzle03

### CODE REVIEW

**Comment by DusanSacha** [comment]
Hmm.. actually there is a problem with `react-scripts` and `node` versions. Check the circleci tests.

**Comment by ovidiubute** [comment]
Probably CircleCI is not running Node 6 for building, you'll need to specify Node 6 in circle.yml. Something like (did not test it): 

```yml
machine:
  node:
    version: 6
```

**Comment by ovidiubute** [comment]
Btw this happened because you upgraded `react-scripts`.

**Comment by DusanSacha** [comment]
Cool, thanks! I pushed a correction.

**Comment by DusanSacha** [comment]
😄 Ok, sorry about removing it.
Btw. can you explain me shortly the warnings in VSCode? Where do they come from? From airbnb-lint as well?

**Comment by ovidiubute** [comment]
I just realized that we don't even have a linting target, we just run prettier 😢  We need a new task in package.json that runs `eslint src/**/*.js`. What you're seeing is vscode's linter actually running so those linting errors are valid. I'll open a new issue, sorry about the confusion.

**Comment by DusanSacha** [comment]
Ok, no problem. Nevertheless I had seen some warnings in the browser after including airbnb (that one about prop-types), so they had to come from somewhere.

**Pull request merged**
